routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('coopNameByUserId/{id}', function ($id){
//
//   $user = \App\Model\User\User::find($id);
//   return $user->coops;
//});

Route::get('/', function () {
    return view('welcome');
});

Route::redirect('/','/admin/login');

//Route::get('locale/{locale}', function ($locale){
//
//   \Illuminate\Support\Facades\Session::put('locale', $locale);
//   \Illuminate\Support\Facades\App::setLocale($locale);
//   return redirect()->back();
//});
//
//



Route::get('large-compact-sidebar/dashboard/dashboard1', function () {
    // set layout sesion(key)
    session(['layout' => 'compact']);
    return view('dashboard.dashboardv1');
})->name('compact');

Route::get('large-sidebar/dashboard/dashboard1', function () {
    // set layout sesion(key)
    session(['layout' => 'normal']);
    return view('dashboard.dashboardv1');
})->name('normal');

Route::get('horizontal-bar/dashboard/dashboard1', function () {
    // set layout sesion(key)
    session(['layout' => 'horizontal']);
    return view('dashboard.dashboardv1');
})->name('horizontal');


Route::view('dashboard/dashboard1', 'dashboard.dashboardv1')->name('dashboard_version_1');
Route::view('dashboard/dashboard2', 'dashboard.dashboardv2')->name('dashboard_version_2');
Route::view('dashboard/dashboard3', 'dashboard.dashboardv3')->name('dashboard_version_3');
Route::view('dashboard/dashboard4', 'dashboard.dashboardv4')->name('dashboard_version_4');

// uiKits
Route::view('uikits/alerts', 'uiKits.alerts')->name('alerts');
Route::view('uikits/accordion', 'uiKits.accordion')->name('accordion');
Route::view('uikits/buttons', 'uiKits.buttons')->name('buttons');
Route::view('uikits/badges', 'uiKits.badges')->name('badges');
Route::view('uikits/bootstrap-tab', 'uiKits.bootstrap-tab')->name('bootstrap-tab');
Route::view('uikits/carousel', 'uiKits.carousel')->name('carousel');
Route::view('uikits/collapsible', 'uiKits.collapsible')->name('collapsible');
Route::view('uikits/lists', 'uiKits.lists')->name('lists');
Route::view('uikits/pagination', 'uiKits.pagination')->name('pagination');
Route::view('uikits/popover', 'uiKits.popover')->name('popover');
Route::view('uikits/progressbar', 'uiKits.progressbar')->name('progressbar');
Route::view('uikits/tables', 'uiKits.tables')->name('tables');
Route::view('uikits/tabs', 'uiKits.tabs')->name('tabs');
Route::view('uikits/tooltip', 'uiKits.tooltip')->name('tooltip');
Route::view('uikits/modals', 'uiKits.modals')->name('modals');
Route::view('uikits/NoUislider', 'uiKits.NoUislider')->name('NoUislider');
Route::view('uikits/cards', 'uiKits.cards')->name('cards');
Route::view('uikits/cards-metrics', 'uiKits.cards-metrics')->name('cards-metrics');
Route::view('uikits/typography', 'uiKits.typography')->name('typography');

// extra kits
Route::view('extrakits/dropDown', 'extraKits.dropDown')->name('dropDown');
Route::view('extrakits/imageCroper', 'extraKits.imageCroper')->name('imageCroper');
Route::view('extrakits/loader', 'extraKits.loader')->name('loader');
Route::view('extrakits/laddaButton', 'extraKits.laddaButton')->name('laddaButton');
Route::view('extrakits/toastr', 'extraKits.toastr')->name('toastr');
Route::view('extrakits/sweetAlert', 'extraKits.sweetAlert')->name('sweetAlert');
Route::view('extrakits/tour', 'extraKits.tour')->name('tour');
Route::view('extrakits/upload', 'extraKits.upload')->name('upload');


// Apps
Route::view('apps/invoice', 'apps.invoice')->name('invoice');
Route::view('apps/inbox', 'apps.inbox')->name('inbox');
Route::view('apps/chat', 'apps.chat')->name('chat');
Route::view('apps/calendar', 'apps.calendar')->name('calendar');
Route::view('apps/task-manager-list', 'apps.task-manager-list')->name('task-manager-list');
Route::view('apps/task-manager', 'apps.task-manager')->name('task-manager');
Route::view('apps/toDo', 'apps.toDo')->name('toDo');
Route::view('apps/ecommerce/products', 'apps.ecommerce.products')->name('ecommerce-products');
Route::view('apps/ecommerce/product-details', 'apps.ecommerce.product-details')->name('ecommerce-product-details');
Route::view('apps/ecommerce/cart', 'apps.ecommerce.cart')->name('ecommerce-cart');
Route::view('apps/ecommerce/checkout', 'apps.ecommerce.checkout')->name('ecommerce-checkout');


Route::view('apps/contacts/lists', 'apps.contacts.lists')->name('contacts-lists');
Route::view('apps/contacts/contact-details', 'apps.contacts.contact-details')->name('contact-details');
Route::view('apps/contacts/grid', 'apps.contacts.grid')->name('contacts-grid');

// forms
Route::view('forms/basic-action-bar', 'forms.basic-action-bar')->name('basic-action-bar');
Route::view('forms/multi-column-forms', 'forms.multi-column-forms')->name('multi-column-forms');
Route::view('forms/smartWizard', 'forms.smartWizard')->name('smartWizard');
Route::view('forms/tagInput', 'forms.tagInput')->name('tagInput');
Route::view('forms/forms-basic', 'forms.forms-basic')->name('forms-basic');
Route::view('forms/form-layouts', 'forms.form-layouts')->name('form-layouts');
Route::view('forms/form-input-group', 'forms.form-input-group')->name('form-input-group');
Route::view('forms/form-validation', 'forms.form-validation')->name('form-validation');
Route::view('forms/form-editor', 'forms.form-editor')->name('form-editor');

// Charts
Route::view('charts/echarts', 'charts.echarts')->name('echarts');
Route::view('charts/chartjs', 'charts.chartjs')->name('chartjs');
Route::view('charts/apexLineCharts', 'charts.apexLineCharts')->name('apexLineCharts');
Route::view('charts/apexAreaCharts', 'charts.apexAreaCharts')->name('apexAreaCharts');
Route::view('charts/apexBarCharts', 'charts.apexBarCharts')->name('apexBarCharts');
Route::view('charts/apexColumnCharts', 'charts.apexColumnCharts')->name('apexColumnCharts');
Route::view('charts/apexRadialBarCharts', 'charts.apexRadialBarCharts')->name('apexRadialBarCharts');
Route::view('charts/apexRadarCharts', 'charts.apexRadarCharts')->name('apexRadarCharts');
Route::view('charts/apexPieDonutCharts', 'charts.apexPieDonutCharts')->name('apexPieDonutCharts');
Route::view('charts/apexSparklineCharts', 'charts.apexSparklineCharts')->name('apexSparklineCharts');
Route::view('charts/apexScatterCharts', 'charts.apexScatterCharts')->name('apexScatterCharts');
Route::view('charts/apexBubbleCharts', 'charts.apexBubbleCharts')->name('apexBubbleCharts');
Route::view('charts/apexCandleStickCharts', 'charts.apexCandleStickCharts')->name('apexCandleStickCharts');
Route::view('charts/apexMixCharts', 'charts.apexMixCharts')->name('apexMixCharts');

// datatables
Route::view('datatables/basic-tables', 'datatables.basic-tables')->name('basic-tables');

// sessions
Route::view('sessions/signIn', 'sessions.signIn')->name('signIn');
Route::view('sessions/signUp', 'sessions.signUp')->name('signUp');
Route::view('sessions/forgot', 'sessions.forgot')->name('forgot');

// widgets
Route::view('widgets/card', 'widgets.card')->name('widget-card');
Route::view('widgets/statistics', 'widgets.statistics')->name('widget-statistics');
Route::view('widgets/list', 'widgets.list')->name('widget-list');
Route::view('widgets/app', 'widgets.app')->name('widget-app');
Route::view('widgets/weather-app', 'widgets.weather-app')->name('widget-weather-app');

// others
Route::view('others/notFound', 'others.notFound')->name('notFound');
Route::view('others/user-profile', 'others.user-profile')->name('user-profile');
Route::view('others/starter', 'starter')->name('starter');
Route::view('others/faq', 'others.faq')->name('faq');
Route::view('others/pricing-table', 'others.pricing-table')->name('pricing-table');
Route::view('others/search-result', 'others.search-result')->name('search-result');


Route::group(['namespace' => 'Admin'], function(){

    // Admin
   Route::get('admin/home','HomeController@index')->name('admin.home');

    // Coop
    Route::resource('admin/coop','CoopController');

    // Coop use
    Route::resource('admin/coop-user', 'CoopUserController');

    // Note
    Route::resource('admin/note','NoteController');

    // Advertisement
    Route::group(['middleware' =>'role:super-admin'], function (){

        // Admin Role
        Route::resource('admin/role','RoleController');

        // Admin user
        Route::resource('admin/admin','AdminController');

        // Admin Permission
        Route::resource('admin/permission','PermissionController');

        // Admin  Advertisement
        Route::resource('admin/advertisement','AdvertisementController');

    });
    // Admin Auth Routes
    Route::get('admin/login','Auth\LoginController@showLoginForm')->name('admin.login');

    // Admin Auth Routes
    Route::post('admin/login','Auth\LoginController@login');


    Route::get('admin/profile/{id}','adminController@profileEdit')->name('admin.profile');
    Route::patch('admin/profile-update/{id}','adminController@profileUpdate')->name('admin.profile-update');



    Route::prefix('admin')->group(function (){ // must add this prefix
        Route::post('password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.reset');
        Route::post('password/reset', 'Auth\AdminResetPasswordController@reset');
        Route::get('password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset.token');

    });


});

Route::get('locale/{locale}',function ($locale){
   // \Illuminate\Support\Facades\Session::put('locale',$locale);
    \Illuminate\Support\Facades\Session::put('locale',$locale);
    //App::setLocale($locale);
    return redirect()->back();
});

Auth::routes();

Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

app/Http/Controllers/Admin/CoopUserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Admin\Coop;
use App\Model\Admin\Coop_User;
use App\Model\Admin\CoopUser;
use App\Model\User\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CoopUserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        //

        //$coops = Coop::where(['admin_id' => auth()->user()->id ]);
        $coops = Coop::all();
        $users = User::all();
        $coopUsers = CoopUser::all();
        return view('admin.coop-user.index',compact('coops', 'users', 'coopUsers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        //
        $users = User::all();
        $coops  = Coop::all();

        return view('admin.coop-user.create', compact('users', 'coops'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $coopUser = new CoopUser;

//        $this->validate($request, [
//
//            'payment_due' => 'required',
//            'coop_id' => 'required',
//            'user_id' => 'required',
//            'amount' => 'required',
//            'status' => 'required',
//        ]);

        $coopUser->payment_due           = Carbon::parse($request->payment_due);
        $coopUser->payment_received        = Carbon::parse($request->payment_received);
        $coopUser->coop_id               = $request->coop_id;
        $coopUser->user_id               = $request->user_id;
        $coopUser->payment               = $request->payment;
        $coopUser->status_payment        = $request->status_payment;
        $coopUser->status_received       = $request->status_received;
        $coopUser->payout                = $request->payout;
        $coopUser->comment               = $request->comment;
        $coopUser->admin_id              = auth()->user()->id;

        //return $coopUser;


       // dd($request->all());

      //  $coopUser->coopsAndUser()->attach(\request('coop'));

     // var_dump($dd);
        //$coopUser->coops_()->sync($request->coop_id);

        //Coop_User::create(['coop_id' =>  $coopUser->coop_id, 'user_id' =>  $coopUser->user_id ]);

        $coopUser->save();
        $coopUser->coopsAndUser()->sync( array(
            1 => array( 'coop_id' => $request->coop_id, 'user_id' => $request->user_id ),));

//        $coopUser->coops_()->sync($request->coop_id);
//        $coopUser->users_()->sync( $request->user_id);


//        $coop_user = new Coop_User();
//        $coopUser->coop_id = $request->coop_id;
//        $coopUser->user_id = $request->user_id;
//        $coop_user->save();


       // return $coopUser;

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $coopUser = CoopUser::findOrFail($id);
        $coops = Coop::all();
        $users = User::all();
        return view('admin.coop-user.edit', compact('coopUser', 'coops', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        $coopUser = CoopUser::findOrFail($id);

        $coopUser->payment_due           = Carbon::parse($request->payment_due);
        $coopUser->payment_receiv        = Carbon::parse($request->payment_received);
        $coopUser->coop_id               = $request->coop_id;
        $coopUser->user_id               = $request->user_id;
        $coopUser->payment               = $request->payment;
        $coopUser->status_payment        = $request->status_payment;
        $coopUser->status_received       = $request->status_received;
        $coopUser->payout                = $request->payout;
        $coopUser->comment               = $request->comment;

        $coopUser->admin_id              = auth()->user()->id;

        $coopUser->save();

        return redirect(route('coop-user.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        CoopUser::where('id',$id)->delete();

        return redirect()->back();
    }
}

resources/views/admin/coop-user/create.blade.php
@extends('admin.layouts.master')
@section('before-css')
    <link rel="stylesheet" href="{{asset('assets/styles/vendor/pickadate/classic.css')}}">
    <link rel="stylesheet" href="{{asset('assets/styles/vendor/pickadate/classic.date.css')}}">


@endsection

@section('main-content')
    <div class="breadcrumb">
        <h1>@lang('coop-user.title')</h1>
{{--        <ul>--}}
{{--            <li><a href="">Form</a></li>--}}
{{--            <li>Basic</li>--}}
{{--        </ul>--}}
    </div>

    <div class="separator-breadcrumb border-top"></div>

    <div class="row">

        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-body">
                    <div class="card-title mb-3">@lang('coop-user.add')</div>
                    <form method="POST" action="{{ route('coop-user.store') }}" >
                        @csrf
                        <div class="row">

                            <div class="col-md-6 form-group mb-3">
                                <label for="coops">@lang('coop-user.select')</label>
                                <select class="form-control form-control-rounded" name="coop_id" id="coop_id">
                                    @foreach($coops as $coop)
                                        @hasanyrole('super-admin|admin')
                                        @if(auth()->id() == $coop->admin_id)
                                    <option value="{{ $coop->id }}">{{ $coop->name }}</option>
                                        @endif
                                        @endhasanyrole
                                        @endforeach
                                </select>
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="users">@lang('coop-user.user')</label>
                                <select class="form-control form-control-rounded" name="user_id" id="user_id">
                                    @foreach($users as $user)
                                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="payment due">@lang('coop-user.payment_due')</label>
                                <input type="date" class="form-control form-control-rounded" id="picker2" name="payment_due" >
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="payment due">@lang('coop-user.payment')</label>
                                <input type="number" class="form-control form-control-rounded" id="payment" name="payment" >
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="status"> @lang('coop-user.status_payment') </label>
                                <select class="form-control form-control-rounded" name="status_payment" id="status_payment">
                                    <option value="" disabled selected> @lang('common.select') </option>
                                    <option value="not-paid">Not Paid - لم يتم الدفع</option>
                                    <option value="paid">تم الدفع - paid</option>
                                    <option value="delay">تأخير في الدفع - Delay</option>
                                </select>
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="payment received">@lang('coop-user.payment_received')</label>
                                <input type="date" class="form-control form-control-rounded" id="picker2" name="payment_received" >
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="status">@lang('coop-user.status_received') </label>
                                <select class="form-control form-control-rounded" name="status_received" id="status" required>
                                    <option value="" disabled selected> @lang('common.select')</option>
                                    <option value="payment received"> Payment Received</option>
                                    <option value="payment not received">Not Received Payment</option>
                                    <option value="delay">Delay</option>
                                </select>
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for=" Comment ">@lang('coop-user.comment')</label>
                                <input type="text" class="form-control form-control-rounded" id="comment" name="comment" >
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="payout">@lang('coop-user.payout')</label>
                                <input type="number" class="form-control form-control-rounded" id="amount" name="payout" >
                            </div>

                            <div class="col-md-12">
                                <button class="btn btn-primary">@lang('coop-user.submit')</button>
{{--                                <a class="btn btn-danger" href="{{ route('coop-user.index') }}">Back to coop user</a>--}}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>


@endsection

@section('page-js')
    <script src="{{asset('assets/js/vendor/pickadate/picker.js')}}"></script>
    <script src="{{asset('assets/js/vendor/pickadate/picker.date.js')}}"></script>



@endsection

@section('bottom-js')
    <script src="{{asset('assets/js/form.basic.script.js')}}"></script>


@endsection

resources/views/admin/coop-user/edit.blade.php
@extends('admin.layouts.master')
@section('before-css')
    <link rel="stylesheet" href="{{asset('assets/styles/vendor/pickadate/classic.css')}}">
    <link rel="stylesheet" href="{{asset('assets/styles/vendor/pickadate/classic.date.css')}}">


@endsection

@section('main-content')
    <div class="breadcrumb">
        <h1>@lang('coop-user.title')</h1>
{{--        <ul>--}}
{{--            <li><a href="">Form</a></li>--}}
{{--            <li>Basic</li>--}}
{{--        </ul>--}}
    </div>

    <div class="separator-breadcrumb border-top"></div>

    <div class="row">

        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-body">
                    <div class="card-title mb-3">@lang('coop-user.add')</div>
                    <form method="POST" action="{{ route('coop-user.update', $coopUser->id) }}" >
                        @csrf
                        @method('PATCH')
                        <div class="row">

                            <div class="col-md-6 form-group mb-3">
                                <label for="coops">@lang('common.select')</label>
                                <select class="form-control form-control-rounded" name="coop_id" id="coop_id">
                                    @foreach($coops as $coop)
                                        @if(auth()->id() == $coop->admin_id)
                                            <option value="{{ $coop->id }}">{{ $coop->name }}</option>
                                        @endif
                                    @endforeach
                                </select>
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="users">@lang('coop-user.user')</label>
                                <select class="form-control form-control-rounded" name="user_id" id="user_id">
                                    @foreach($users as $user)
                                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="payment due">@lang('coop-user.payment_due')</label>
                                <input type="date" class="form-control form-control-rounded" id="picker2" name="payment_due" value="{{ $coopUser->payment_due }}" >
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="payment due">@lang('coop-user.payment')</label>
                                <input type="number" class="form-control form-control-rounded" id="payment" name="payment" value="{{ $coopUser->payment }}">
                            </div>


                            <div class="col-md-6 form-group mb-3">
                                <label for="status">@lang('coop-user.status_payment')</label>
                                <select class="form-control form-control-rounded" name="status_payment" id="status_payment">
                                    <option value="" disabled selected> @lang('common.select') </option>
                                    <option value="not-paid">Not Paid - لم يتم الدفع</option>
                                    <option value="paid">تم الدفع - paid</option>
                                    <option value="delay">تأخير في الدفع - Delay</option>
                                </select>
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="payment due">@lang('coop-user.payment_received')</label>
                                <input type="date" class="form-control form-control-rounded" id="picker2" name="payment_received"  value="{{ $coopUser->payment_received }}">
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="status">@lang('coop-user.status_received') </label>
                                <select class="form-control form-control-rounded" name="status_received" id="status" required>
                                    <option value="" disabled selected> @lang('common.select')</option>
                                    <option value="payment received"> Payment Received</option>
                                    <option value="payment not received">Not Received Payment</option>
                                    <option value="delay">Delay</option>
                                </select>
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for=" Comment">@lang('coop-user.comment')</label>
                                <input type="text" class="form-control form-control-rounded" id="comment" name="comment" value="{{ $coopUser->comment }}" >
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="payout">@lang('coop-user.payout')</label>
                                <input type="number" class="form-control form-control-rounded" id="payout" name="payout" value="{{ $coopUser->payout }}" >
                            </div>

                            <div class="col-md-12">
                                <button class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>


@endsection

@section('page-js')
    <script src="{{asset('assets/js/vendor/pickadate/picker.js')}}"></script>
    <script src="{{asset('assets/js/vendor/pickadate/picker.date.js')}}"></script>



@endsection

@section('bottom-js')
    <script src="{{asset('assets/js/form.basic.script.js')}}"></script>


@endsection